# Generated by Django 3.2.3 on 2021-08-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treck', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
